var express = require('express')
var app = express()

var apiUsuarios = require('./api/usuarios')
var apiRoles = require('./api/roles')
var apiInformes = require('./api/informes')
var apiEstadoPreguntasOriginales = require('./api/estadoPreguntasOriginales')
var apiEstadoDerivaciones = require('./api/estadoDerivaciones')
var apiMotivosConsolidacion = require('./api/motivosConsolidacion')
var apiAutores = require('./api/autores')
var apiOrganismos = require('./api/organismos')
var apiPermisos = require('./api/permisos')
var apiRespuestas = require('./api/respuestas')
var apiDerivaciones = require('./api/derivaciones')
var apiAuth = require('./auth/routes')

app.use('/api/usuarios', apiUsuarios)
app.use('/api/derivaciones', apiDerivaciones)
app.use('/api/respuestas', apiRespuestas)
app.use('/api/informes', apiInformes)
app.use('/api/roles', apiRoles)
app.use('/api/estado_derivaciones', apiEstadoDerivaciones)
app.use('/api/estado_preguntas_originales', apiEstadoPreguntasOriginales)
app.use('/api/motivos_consolidacion', apiMotivosConsolidacion)
app.use('/api/autores', apiAutores)
app.use('/api/organismos', apiOrganismos)
app.use('/api/permisos', apiPermisos)
app.use('/api/token', apiAuth)

module.exports = app