# latest official node image
FROM node:8.9.0

MAINTAINER Leandro Ferrigno <lferrigno@cys.com.ar>

# use nodemon for development
# RUN npm config set proxy http://10.1.1.25:8080/
# RUN npm config set https-proxy http://10.1.1.25:8080/
# RUN npm install --global webpack webpack-dev-server
RUN mkdir -p /usr/src

WORKDIR /usr/src

EXPOSE 3000
EXPOSE 9229 

CMD [ "npm","run", "start-dock-dev" ]


