version: '3'
services:
  nodeBack:
    image: node-back
    container_name: nodeBack
    ports:
      - "3050:3000"
      - "3051:3001"
      - "9229:9229"
    tty: true
    volumes:
      - ../:/usr/src
    links:
     - db:database
  db:
    container_name: postgres
    image: postgres8.4.1
    restart: always
#    ports:
#     - "3052:5432"
    environment:
      POSTGRES_PASSWORD: example
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #   - 8080:8080