'use strict'
var bcrypt = require('bcrypt')

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('autor', [
      {nombre: 'AGUILAR EDUARDO ALBERTO',
        descripcion: 'AGUILAR EDUARDO ALBERTO',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'ALMIRÓN ANA CLAUDIA',
        descripcion: 'ALMIRÓN ANA CLAUDIA',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'ALPEROVICH JOSÉ JORGE',
        descripcion: 'ALPEROVICH JOSÉ JORGE',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'BASUALDO ROBERTO GUSTAVO',
        descripcion: 'BASUALDO ROBERTO GUSTAVO',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'BLAS INÉS IMELDA',
        descripcion: 'BLAS INÉS IMELDA',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'BOYADJIAN MIRIAM RUTH',
        descripcion: 'BOYADJIAN MIRIAM RUTH',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'BRAILLARD POCCARD NÉSTOR PEDRO',
        descripcion: 'BRAILLARD POCCARD NÉSTOR PEDRO',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'BRIZUELA Y DORIA DE CARA OLGA INES',
        descripcion: 'BRIZUELA Y DORIA DE CARA OLGA INES',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'BULLRICH ESTEBAN JOSE',
        descripcion: 'BULLRICH ESTEBAN JOSE',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'CASERIO CARLOS ALBERTO',
        descripcion: 'CASERIO CARLOS ALBERTO',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'CASTILLO OSCAR ANÍBAL',
        descripcion: 'CASTILLO OSCAR ANÍBAL',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'CATALÁN MAGNI JULIO CÉSAR',
        descripcion: 'CATALÁN MAGNI JULIO CÉSAR',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'CATALFAMO MARIA EUGENIA',
        descripcion: 'CATALFAMO MARIA EUGENIA',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'CLOSS MAURICE FABIAN',
        descripcion: 'CLOSS MAURICE FABIAN',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'COBOS JULIO CÉSAR CLETO',
        descripcion: 'COBOS JULIO CÉSAR CLETO',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'COSTA EDUARDO RAUL',
        descripcion: 'COSTA EDUARDO RAUL',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'CREXELL CARMEN LUCILA',
        descripcion: 'CREXELL CARMEN LUCILA',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'DE ANGELI ALFREDO LUIS',
        descripcion: 'DE ANGELI ALFREDO LUIS',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'DURANGO NORMA HAYDÉE',
        descripcion: 'DURANGO NORMA HAYDÉE',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'ELÍAS DE PEREZ SILVIA BEATRIZ',
        descripcion: 'ELÍAS DE PEREZ SILVIA BEATRIZ',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'ESPÍNOLA CARLOS MAURICIO',
        descripcion: 'ESPÍNOLA CARLOS MAURICIO',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'FERNÁNDEZ DE KIRCHNER CRISTINA E.',
        descripcion: 'FERNÁNDEZ DE KIRCHNER CRISTINA E.',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'FERNÁNDEZ SAGASTI ANABEL',
        descripcion: 'FERNÁNDEZ SAGASTI ANABEL',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'FIAD MARIO RAYMUNDO',
        descripcion: 'FIAD MARIO RAYMUNDO',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'FIORE VIÑUALES MARÍA CRISTINA DEL VALLE',
        descripcion: 'FIORE VIÑUALES MARÍA CRISTINA DEL VALLE',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'FUENTES MARCELO JORGE',
        descripcion: 'FUENTES MARCELO JORGE',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'GARCÍA LARRABURU SILVINA MARCELA',
        descripcion: 'GARCÍA LARRABURU SILVINA MARCELA',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'GIACOPPO SILVIA DEL ROSARIO',
        descripcion: 'GIACOPPO SILVIA DEL ROSARIO',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'GONZALEZ GLADYS ESTHER',
        descripcion: 'GONZALEZ GLADYS ESTHER',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'GONZÁLEZ MARÍA TERESA MARGARITA',
        descripcion: 'GONZÁLEZ MARÍA TERESA MARGARITA',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'GONZÁLEZ NANCY SUSANA',
        descripcion: 'GONZÁLEZ NANCY SUSANA',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'GUASTAVINO PEDRO GUILLERMO ÁNGEL',
        descripcion: 'GUASTAVINO PEDRO GUILLERMO ÁNGEL',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'IANNI ANA MARIA',
        descripcion: 'IANNI ANA MARIA',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'ITÚRREZ DE CAPPELLINI ADA ROSA DEL VALLE',
        descripcion: 'ITÚRREZ DE CAPPELLINI ADA ROSA DEL VALLE',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'KUNATH SIGRID ELISABETH',
        descripcion: 'KUNATH SIGRID ELISABETH',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'LOPEZ VALVERDE CRISTINA DEL CARMEN',
        descripcion: 'LOPEZ VALVERDE CRISTINA DEL CARMEN',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'LOVERA DANIEL ANÍBAL',
        descripcion: 'LOVERA DANIEL ANÍBAL',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'LUENZO ALFREDO HÉCTOR',
        descripcion: 'LUENZO ALFREDO HÉCTOR',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'MARINO JUAN CARLOS',
        descripcion: 'MARINO JUAN CARLOS',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'MARTINEZ JULIO CESAR',
        descripcion: 'MARTINEZ JULIO CESAR',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'MARTÍNEZ ERNESTO FÉLIX',
        descripcion: 'MARTÍNEZ ERNESTO FÉLIX',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'MAYANS JOSÉ MIGUEL ÁNGEL',
        descripcion: 'MAYANS JOSÉ MIGUEL ÁNGEL',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'MENEM CARLOS SAÚL',
        descripcion: 'MENEM CARLOS SAÚL',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'MERA DALMACIO',
        descripcion: 'MERA DALMACIO',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'MIRKIN BEATRIZ GRACIELA',
        descripcion: 'MIRKIN BEATRIZ GRACIELA',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'MONTENEGRO GERARDO ANTENOR',
        descripcion: 'MONTENEGRO GERARDO ANTENOR',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'ODARDA MARÍA MAGDALENA',
        descripcion: 'ODARDA MARÍA MAGDALENA',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'OJEDA JOSÉ ANATOLIO',
        descripcion: 'OJEDA JOSÉ ANATOLIO',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'PAIS JUAN MARIO',
        descripcion: 'PAIS JUAN MARIO',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'PEREYRA GUILLERMO JUAN',
        descripcion: 'PEREYRA GUILLERMO JUAN',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'PEROTTI OMAR ÁNGEL',
        descripcion: 'PEROTTI OMAR ÁNGEL',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'PETCOFF NAIDENOFF LUIS CARLOS',
        descripcion: 'PETCOFF NAIDENOFF LUIS CARLOS',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'PICHETTO MIGUEL ÁNGEL',
        descripcion: 'PICHETTO MIGUEL ÁNGEL',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'PILATTI VERGARA MARÍA INÉS',
        descripcion: 'PILATTI VERGARA MARÍA INÉS',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'PINEDO FEDERICO',
        descripcion: 'PINEDO FEDERICO',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'POGGI CLAUDIO JAVIER',
        descripcion: 'POGGI CLAUDIO JAVIER',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'PORCEL DE RICCOBELLI BLANCA',
        descripcion: 'PORCEL DE RICCOBELLI BLANCA',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'REUTEMANN CARLOS ALBERTO',
        descripcion: 'REUTEMANN CARLOS ALBERTO',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'RODRÍGUEZ MACHADO LAURA ELENA',
        descripcion: 'RODRÍGUEZ MACHADO LAURA ELENA',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'RODRÍGUEZ SAÁ ADOLFO',
        descripcion: 'RODRÍGUEZ SAÁ ADOLFO',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'ROMERO JUAN CARLOS',
        descripcion: 'ROMERO JUAN CARLOS',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'ROZAS ÁNGEL',
        descripcion: 'ROZAS ÁNGEL',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'SACNUN MARÍA DE LOS ÁNGELES',
        descripcion: 'SACNUN MARÍA DE LOS ÁNGELES',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'SCHIAVONI HUMBERTO LUIS ARTURO',
        descripcion: 'SCHIAVONI HUMBERTO LUIS ARTURO',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'SNOPEK GUILLERMO EUGENIO MARIO',
        descripcion: 'SNOPEK GUILLERMO EUGENIO MARIO',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'SOLANAS FERNANDO EZEQUIEL',
        descripcion: 'SOLANAS FERNANDO EZEQUIEL',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'SOLARI  QUINTANA MAGDALENA',
        descripcion: 'SOLARI  QUINTANA MAGDALENA',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'TAPIA MARIA BELEN',
        descripcion: 'TAPIA MARIA BELEN',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'UÑAC JOSE RUBEN',
        descripcion: 'UÑAC JOSE RUBEN',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'URTUBEY RODOLFO JULIO',
        descripcion: 'URTUBEY RODOLFO JULIO',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'VARELA MARTA',
        descripcion: 'VARELA MARTA',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {nombre: 'VERASAY PAMELA FERNANDA',
        descripcion: 'VERASAY PAMELA FERNANDA',
        camara: 'HSN',
        created_at: new Date(),
        updated_at: new Date(),
      }
    ], {})
  },

  down: (queryInterface, Sequelize) => {
    /*
      Add reverting commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      return queryInterface.bulkDelete('Person', null, {})
    */
  }
}